name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cd rust
        cargo build --verbose
    - name: Run tests
      run: |
        cd rust
        cargo build --verbose
  release:
  runs-on: [self-hosted]
  if: github.ref == 'refs/heads/main'

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Utilisez une version de Node.js 15.x ou supérieure

    - name: Install dependencies
      run: npm install

    - name: Run semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: npx semantic-release